### ISSUE TITLE
Object property examples not displayed

### ISSUE THREAD

**Issue by bircow** [DapperDox/dapperdox#59]
Definitions with "inline" property example values, i.e. with `example` along with property, are not displayed in at resource page.

Definition like this

````yaml
  UserMeResponse:
    type: object
    title: User object
    properties:
      id:
        type: integer
        minimum: 0
        description: User ID.
        example: 2929                 # << property example
      first_name:
        type: string
        description: User's first or given name.
        example: John
      last_name:
        type: string
        description: User's last or family name.
        example: Appleseed
      email:
        type: string
        format: email
        description: User's email.
        example: john@apple.com
      phone:
        type: string
        description: User's phone.
        example: +123 558 951 14
    required:
      - id
      - email
````
have no example at resource page. But modified to:

````yaml
  UserMeResponse:
    type: object
    title: User object
    properties:
      id:
        type: integer
        minimum: 0
        description: User ID.
      first_name:
        type: string
        description: User's first or given name.
      last_name:
        type: string
        description: User's last or family name.
      email:
        type: string
        format: email
        description: User's email.
      phone:
        type: string
        description: User's phone.
    required:
      - id
      - email
    example:                # << object example
      id: 2929
      first_name: "John"
      last_name: "Appleseed"
      email: "john@apple.com"
      phone: "+123 558 951 14"
````
has example section
![selection_026](https://user-images.githubusercontent.com/383059/26933658-6e06fa08-4c67-11e7-83c7-5ffb668a1616.png)

IMHO property examples should be silently loss. Other tools, like editor.swagger.io, displays them. 

Question is what examples take precedence. Editor.swagger.io overrides property example if there is the object example.
